# Generated by Django 4.1.2 on 2022-10-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="cif_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cif_fk",
                to="bank.customer",
            ),
        ),
    ]
